### ISSUE TITLE
Submit ally fix

### ISSUE THREAD

**Issue by flukejones** [hhd-dev/linux-handheld#3] opened 2024-09-17 09:57 UTC
Please submit the patch https://github.com/hhd-dev/linux-handheld/blob/master/6.6/v1-ally-fix.patch upstream.

I spent many many hours narrowing down the cause of this rather annoying issue and shared a lot of data and info which I assume got back to you - if any of it helped please credit. It's a little frustrating for me as I knew exactly what needed to be done here but had little knowledge of suspend or time to work on it in the end.

In any case, I've tested and it looks like this can be put to rest.

If you submit upstream I'll add my tested-by and reviewed-by tags plus okay it for the asus-wmi driver (or I can do that patch, but easier to send both as a chain to required mailing lists).

If sending to LKML isn't something you want to deal with I understand - I can send on your behalf if it helps.

**Comment by antheas** [comment] 2024-09-17 15:56
Hi Luke,
yes, I plan on submitting the patch to LKML. Please allow for the proper testing of the patch beforehand and for me to get feedback from Mario as this patch can affect many devices. 

For context, this is the first version I made of the patch. I made it yesterday and it happened to work perfectly without any tweaking. I also spent around 20-30 hours researching for it during preparing support for the Ally X in July.

Also, if you do in fact believe this patch solves this issue, you should inform Asus immediately so that they do not waste engineering resources producing a new firmware and then complicating the situation further.

> if any of it helped please credit. It's a little frustrating for me as I knew exactly what needed to be done here but had little knowledge of suspend

This is a bit of a complicated topic, as it is hard for me to find where to credit you. Yes, your prior work that is upstream as of 6.11 helped a lot in diagnosing this issue. However, any work past that did not.

For context, I was the one that found out the powersave bug and reported it to Derek and in extension to you. Futhermore, during my testing for the Ally X support in July (for which you did not credit me), I made over 25 patch variations to figure out the issue. 

During that testing, I made a patch in which I added 4 seconds between the display on and off calls to give the MCU ample time to wake up, and it made no difference, by using an lsb0 handler similar to what you did prior to submitting the CSEE patch for the original Ally. This patch included print statements. Looking at dmesg, I saw those print messages happened after the EC interrupts were disabled. This made it clear to me that that was the issue, as 4 seconds are ample time for any wakeup to occur.

After our little scuffle at lore, I forwarded all of this information to Derek, by telling him that calling CSEE twice, once as part of asus-wmi and once as part of _DSM Display On/Off is not a proper solution and the problem here appears to be that the Display On/Off call happens after the EC interrupts block. If you had just commented out the DSM parts, your suspend quirk that is on 6.11 would have worked perfectly and you would know what the issue was.

In turn, you received this information, which turned into Mario producing a new patchset in [superm1/dsm-screen-on-off](https://git.kernel.org/pub/scm/linux/kernel/git/superm1/linux.git/log/?h=superm1/dsm-screen-on-off).

I thought great, hopefully this is fixed now, only to find you producing patches on top of it that reproduced the same issue, by calling the CSEE function on top of the broken _DSM calls, either directly or through the display on/off callbacks that are only supposed to be called by drm drivers. Yesterday, I cloned Mario's branch, compiled it and put it on my new Ally X unit, only to find out that the callbacks Mario added happen after the EC interrupts block, showing to me you still did not understand the issue (Mario does not have a unit to verify after all).

After that, I looked over Mario's patches, seeing that they are not salvageable (they just make things more complicated; like if a display is missing we do not call the _DSM callbacks?) and started a-new by studying the kernel suspend handlers and moving the DSM calls in the beginning of the suspend sequence. I compiled this patch, put it on the Ally X and it worked perfectly on the first try.

Therefore, from my account of the story, I found the bug, I found out why it happens and I even reported both the bug and why it happened to you. Then, due to force majeure, I did not get my Ally X in time, giving you ample time to fix this issue. Finally, I composed a patch with completely new code that is derived from neither Mario's branch nor your patches and it works perfectly.

So I am not sure how I can credit you here. Yes it is unfortunate you spent a lot of time on this issue. All I can say is that it is spilled milk and move forward.

For me, the next step for the Ally X is adding support for the Egis fingerprint scanner. Hopefully I will get to testing your gamepad patch soon as well.

**Comment by flukejones** [comment] 2024-09-17 16:27
I am through with trying to work with you.

**Comment by antheas** [comment] 2024-09-17 20:03
Ok, after reaching out to Mario, I did a lot more testing today. As I told you my patch worked first try.

I tried having a single quirk in asus-wmi with _DSM removed, with or without delays, and moving _DSM from early to to prepare in lsb0, none of them work.

Therefore, I will grant me the fact that I was more than lucky and recognize some of your work. So you should be credited in the patch. As I said before though I do not know how that should look.

I will still note that I reached this patch independently, and I have not been following your conversations in Discord closely. You can thank Derek for that.

Also, Mario is hesitant about including such a change in the kernel and so am I. So you should not expect this to be insta-merged or something of the sort. I would still like to avoid resorting to a firmware change, as I have too many users that do not dual boot and for those it is not an option.

**Comment by NeroReflex** [comment] 2024-09-17 20:15
```sh
git remote add linux-next <url>
git checkout v6.11
git checkout -b anybranch
git am <yourpatch>
# compile and install
```

Hilariously fails with clang and LTO. First try spurios wakup after one minute. pressing A,B,X or Y buttons wakes up the device too.

This is the most spectacularly failing patch I have ever seen in a year.

And I have a fully updated MCU and BIOS.

This is how the console is supposed to sleep:
https://neroreflex.duckdns.org/VID_20240917_214919301.mp4

This is your attempt and is hilarious:
https://neroreflex.duckdns.org/VID_20240917_213957999.mp4
https://neroreflex.duckdns.org/VID_20240917_213204240.mp4
https://neroreflex.duckdns.org/VID_20240917_212338797.mp4

I want to hope that you were joking about taking more than a month to produce this.

**Comment by NeroReflex** [comment] 2024-09-17 20:42
> I think I said I made it yesterday. My Ally arrived on thursday and i had some serious bugs to fix beforehand.
> 
> > First try spurios wakup after one minute. pressing A,B,X or Y buttons wakes up the device too.
> 
> All my patch does is move the call higher. I cannot be blamed for spurious wakeups. As for the ABXY wakeup, it is not clear to me whether the device should wakeup after pressing those buttons but I would not consider that a failure.
> 
> Thank you for testing on an original Ally and showing it works. Can you also do powersave and try again?

Then moving the call higher the way you do introduces regressions. I have not recorded mcu_powersave on, so there is no video of it. Anyway if you really came up with with this all by yourself you would know why it's not even needed.

**Comment by antheas** [comment] 2024-09-17 20:44
Looks needed to me and works great. Works so great in fact that it makes hhd look slow AF and I will have to fix it.

**Comment by NeroReflex** [comment] 2024-09-17 20:48
Have as much fun as you want, but please keep this non-working pile of stuff to yourself. Next time you pretend to fully understand some hardware at least do some research beforehand.

**Closed** 2024-09-17 21:27 UTC
